defmodule Paperwork.Repo.Migrations.AddUniqueAssetNumber do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:assets, [:asset_number], name: "assets_unique_asset_number_index")
  end

  def down do
    drop_if_exists unique_index(:assets, [:asset_number],
                     name: "assets_unique_asset_number_index"
                   )
  end
end
