defmodule Paperwork.Repo.Migrations.AddedProcessAssetForm do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:process_assets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :date_submitted, :date, default: fragment("CURRENT_DATE")
      add :phone_number, :text
      add :department, :text
      add :reason_for_request, :text
      add :asset_changes_requested, :text
      add :process_status, :text, default: "submitted"
      add :current_step, :text, default: "initial_review"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :requestor_id,
          references(:users,
            column: :id,
            name: "process_assets_requestor_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :asset_id,
          references(:assets,
            column: :id,
            name: "process_assets_asset_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:process_assets, "process_assets_requestor_id_fkey")

    drop constraint(:process_assets, "process_assets_asset_id_fkey")

    drop table(:process_assets)
  end
end
